### ISSUE TITLE
Documentation for using an alternative Open AI compatible API / not working with text-generation-webui

### ISSUE THREAD

**Issue by NetroScript** [purton-tech/bionicgpt#29]
### Overview

The documentation states that it is possible to use any OpenAI-compatible API.
As I have a local working installation of `text-generation-webui` I attempted to use this with my already installed models, using the OpenAI compatible API it provides ([text-generation-webui OpenAI Extension](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai)), but encountered issues with chat completion and file embeddings. I was only able to manually fix the chat completion.

Currently there is no documentation at all how to approach it. and I do not know if my method would be the correct one.

### Changes made for deployment

Not needing the `llm-api` (as I am providing my own) I removed that from the docker compose file.

After skimming through the code, to see what I potentially need to change, I identified the envoy configuration for proxying / combining the several services. 

To be able to have a different configuration, I used the following docker service instead, which maps my own config file:

```yaml
  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/purton-tech/bionicgpt-envoy:1.0.3
    ports:
      - "7800:7700"
      - "7801:7701"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
```

I kept the `envoy.yaml` file which is provided in the `.devcontainer` mostly unchanged besides manually running the `sed` commands which are defined in the `Earthfile`. 

I only changed the last section for the LLM API besides that. My changed configuration is as follows:

```yml
  # The LLM API
  - name: llm-api
    connect_timeout: 10s
    type: strict_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: llm-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.docker.internal
                port_value: 5001
```

I am using `host.docker.internal` as `text-generation-webui` is running on the host system, with `5001` being the default port for the OpenAI compatible API. 

With these changes, the docker-compose stack correctly boots and all components are seemingly accessible (using the default auth URL, I can reach the main UI).

### Problems Occuring

* When using the Chat Console and sending a message, the UI is stuck at `Processing prompt...`, it is not possible to cancel this process
  * In the Network view of the browser, I can see that a `completions` API request is correctly done.
  * In the console log of `text-generation-webui` I see that the request is processed, and a response is generated
* When using Team Documents, you can upload files and it will start creating embeddings, but at the end of the progress it will show that all embeddings have failed

### Expectation

Both chat completion and embeddings should work.

### The cause of the problem

I do not know why the embeddings do not work, when manually calling the API (also using the envoy proxy) a correct response gets returned.

**But I did find the problem for the chat completion. Which is casued by the response containing `\r`**

In the file `crates/asset-pipeline/web-components/streaming-chat.ts` lines are currently split by just `\n` :

https://github.com/purton-tech/bionicgpt/blob/91ba40467d011b0d7fc998e78c85f2a663812fae/crates/asset-pipeline/web-components/streaming-chat.ts#L39

Replacing this with:

```TS
const arr = value.split(/\r?\n/);
```

fixes the problem of chat completion. (Which I locally verified by creating an override for the generated index.js)

### Conclusion

Chat completion with `text-generation-webui` as LLM backend doesn't work (at least on Windows), as the Chat responses include carriage returns [which might be a issue specific to `text-generation-webui`]. Embeddings also do not work, although I could not identify what the cause for that is, as neither `text-generation-webui` nor BionicGPT log anything.

**Comment by ianpurton** [comment]
@NetroScript Firstly, thanks for spending the time to raise this well written in depth issue.

So the actions I'll take from this are.

1. Document the approach of using an external (to the docker stack) LLM. 
2. Somehow make the envoy changes configurable in the `docker-compose.yml`. 
3. Integrate your PR.
4. Cancelling a prompt is something we are aware of, LoalAI which we are using doesn't have this. I'm not sure if it's part of the Open AI API. Need to investigate.
5. Investigate why the embeddings don't work

**Comment by ianpurton** [comment]
@NetroScript One issue we've had in the past is the rust pgvector library silently failing on some inputs.

It's called here

https://github.com/purton-tech/bionicgpt/blob/main/crates/embeddings-job/src/main.rs#L24

Is it possible for you to share the document you used for testing the upload?

**Comment by NetroScript** [comment]
> So in the `embeddings-job` section of the `docker-compose.yml` you'll need to set
> 
> `OPENAI_ENDPOINT: http://llm-api:5001` this will route via envoy to you external LLM. You could probably also use `OPENAI_ENDPOINT: http://host.docker.internal:5001`

I can confirm that setting this correctly calls the endpoint, and it then creates the embeddings. (As long as you are using a embedding model in `text-generation-webui` which has a dimension of 384, I used `BAAI/bge-small-en-v1.5` in this case).

But the same environment variable is additionally missing in the `app` service for it to work during chat too:
https://github.com/purton-tech/bionicgpt/blob/2e6636c3873e159f76292d4843502f6ac8e39279/crates/open-api/src/lib.rs#L49

![image](https://github.com/purton-tech/bionicgpt/assets/18115780/c2a33d5c-fe89-4af3-90c5-6ad11c2bcc62)


It would also be nice if the used embedding size could be configured, as 384 can be quite short. (Or also a configuration to return the k-nearest embeddings, so that the LLM models have more context).

------------------------------

Considering:

> Cancelling a prompt is something we are aware of, LoalAI which we are using doesn't have this. I'm not sure if it's part of the Open AI API. Need to investigate.

At least according to [this discussion](https://community.openai.com/t/how-to-abort-create-chat-completion-streaming-i-use-nodejs-typescript/377319/6) on the OpenAI forum the API should support aborting.

I also locally tested the `text-generation-webui` and it also allows closing the connection and then just not generating anymore.

Using an AbortController as described in this [blog post](https://www.builder.io/blog/stream-ai-javascript) seems to work perfectly fine.

But what I mainly also was referring to (but didn't actually write out) is that if the request errors, no error will be displayed, instead the user is "stuck" on `Processing prompt` until he reloads, where then the same request is made.

**Comment by ianpurton** [comment]
Lot's to think about there, thanks.

We do have a user interface for changing the model API base address and we should probably do the same for embeddings.


- [ ] Implement Streaming Abort - reference https://www.builder.io/blog/stream-ai-javascript
- [ ] Document the embeddings strategy.
- [ ] Can we make the 384 configurable, how does that impact pgVector
- [ ] We can set the model location in the models screen, but that might not work without envoy
- [ ] Can we allow the user to set external models via the user interface.

External Models - Possible solution

- Do the reverse proxy in the axum server
- Route the incoming streaming request based on the model parameter in the json call.

**Comment by spreck** [comment]
Does this work now? I'm trying to use other models that I have running locally. I've added this in the Model Setup section of BionicGPT:
Integrate a Model
Prompt Name
WizardCoder-Python-13B-V1.0-GPTQ
Make the name memorable and imply it's usage.
The Base URL of the model
host.docker.internal:5001 (also tried http://127.0.0.1:5001/v1)
The URL location of the OpenAI compatible API
How many billion parameters is the model
13
This is used only for information purposes.
Context Size (bytes)
8192
How much data can be passed to the prompt

I've also tried to setup a new prompt template but while the model shows up in the dropdown, it defaults to the ggml-gpt4all-j model after I click submit.

However I get the following message when I try to test it.

bionicgpt-llm-api-1         | rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:37961: connect: connection refused"
bionicgpt-app-1             | 2023-10-02T20:30:58.109510Z  INFO open_api: Processing 384 bytes
bionicgpt-barricade-1       | [2023-10-02T20:30:58Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 391.899µs
bionicgpt-barricade-1       | [2023-10-02T20:30:58Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 284.899µs
bionicgpt-barricade-1       |
bionicgpt-barricade-1       |     SELECT
bionicgpt-barricade-1       |       id,
bionicgpt-barricade-1       |       user_id,
bionicgpt-barricade-1       |       session_verifier,
bionicgpt-barricade-1       |       otp_code_confirmed,
bionicgpt-barricade-1       |       otp_code_encrypted,
bionicgpt-barricade-1       |       otp_code_attempts,
bionicgpt-barricade-1       |       otp_code_sent
bionicgpt-barricade-1       |     FROM
bionicgpt-barricade-1       |       sessions
bionicgpt-barricade-1       |     WHERE
bionicgpt-barricade-1       |       id = $1

I tried editing the first two sections of docker-compose.yml file to look like this:

services:

  # LocalAI with pre-loaded ggml-gpt4all-j
  #llm-api:
  #  image: ghcr.io/purton-tech/bionicgpt-model-api:latest

  # Handles parsing of multiple documents types.
  unstructured:
    image: quay.io/unstructured-io/unstructured-api:0.0.34
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/purton-tech/bionicgpt-envoy:1.0.3
    ports:
      - "7800:7700"
      - "7801:7701"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
     
The rest of the docker-compose.yml is as default.

I've also downloaded the envoy.yaml file and added a section at the end so it looks like this and placed it in the same directory as the docker-compose.yml file (there was no  # The LLM API section in the default that I downloaded) :

  # The web application
  - name: app
    connect_timeout: 1.25s
    type: strict_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: development
                port_value: 7703
  # The LLM API
  - name: llm-api
    connect_timeout: 10s
    type: strict_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: llm-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.docker.internal
                port_value: 5001

However when I try docker-compose up now I get this message: "no healthy upstream" when I go to http://localhost:7800/

I know the API works because I can use it with autogen in a jupyter notebook by setting these parameters:
import autogen
# Your model configuration for the local OpenAI endpoint
config_list = [
    {
        'model': 'vicuna-13b-v1.5-16k.Q5_K_M.gguf', 
        'api_key': 'sk-111111111111111111111111111111111111111111111111',
        'api_base': 'http://127.0.0.1:5001/v1',
    },
]

**Comment by ianpurton** [comment]
@spreck I did some work around external models so that no envoy config would be necessary.

I'm currently testing that with an external provider. When I get that working, I should be able to get your use case working too.

I'll update this when I'm there.

**Comment by ianpurton** [comment]
The latest version of BionicGPT should be fixed for this.

Documentation is here https://bionic-gpt.com/docs/running-locally/external-api/

No more envoy config

Note, you'll need to do a `docker-compose down -v` to make sure the DB gets reset.

Let me know if you're able to try this and how it went. Thanks

**Comment by NetroScript** [comment]
> The latest version of BionicGPT should be fixed for this.
> 
> Documentation is here [bionic-gpt.com/docs/running-locally/external-api](https://bionic-gpt.com/docs/running-locally/external-api/)
> 
> No more envoy config
> 
> Note, you'll need to do a `docker-compose down -v` to make sure the DB gets reset.
> 
> Let me know if you're able to try this and how it went. Thanks

I quickly skimmed through the documentation (although I personally don't have time to test it myself currently), and it looks nice. But one suggestion came to my mind:

Maybe it would be best if the embedding endpoint doesn't need an API URL defined in the environment. Instead, if the requesting application (assuming the endpoint is sufficiently secured) could just point to an embedding API, it would allow the user interface to define multiple LLM / embedding endpoints. This can maybe later be extended to supporting different embedding models (and thus sizes) for the entire application as an additional configuration option in most likely the *Models & Fine Tuning* section.

**Comment by spreck** [comment]
@ianpurton Thanks for taking the time to look at this, I've finally had a chance to try this fix.

text-generation-webui shows this as my local API: 

> OpenAI compatible API ready at: OPENAI_API_BASE=http://127.0.0.1:5001/v1

I attempted to follow the instructions but maybe I need a new docker_compose.yml?

Here is the one I'm using based on the directions.

```
services:

  # LocalAI with pre-loaded ggml-gpt4all-j
  #llm-api:
   # image: ghcr.io/purton-tech/bionicgpt-model-api:latest

  # Handles parsing of multiple documents types.
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:db264d8
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/purton-tech/bionicgpt-envoy:1.1.3
    ports:
      - "7800:7700"

  # Postgres pre-loaded with pgVector
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: finetuna
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/purton-tech/bionicgpt-db-migrations:1.1.3
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # Barricade handles all /auth routes for user sign up and sign in.
  barricade:
    image: purtontech/barricade
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
        FORWARD_URL: app
        FORWARD_PORT: 7703
        REDIRECT_URL: /app/post_registration
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  #embeddings-job:
   # image: ghcr.io/purton-tech/bionicgpt-embeddings-job:1.1.3
   # environment:
   #   APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
   # depends_on:
   #   db:
    #    condition: service_healthy
   #   migrations:
   #     condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/purton-tech/bionicgpt:1.1.3
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  embeddings-job:
      image: ghcr.io/purton-tech/bionicgpt-embeddings-job:1.0.3
      environment:
        OPENAI_ENDPOINT: http://llm-api:5001
        APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable

```
http://localhost:5001/v1/models looks like this:

> {"object": "list", "data": [{"id": "TheBloke_MythoMax-L2-13B-GPTQ_gptq-4bit-32g-actorder_True", "object": "model", "owned_by": "user", "permission": []}, {"id": "all-mpnet-base-v2", "object": "model", "owned_by": "user", "permission": []}, {"id": "gpt-3.5-turbo", "object": "model", "owned_by": "user", "permission": []}, {"id": "text-embedding-ada-002", "object": "model", "owned_by": "user", "permission": []}, {"id": "codellama-34b-python.Q5_K_M.gguf", "object": "model", "owned_by": "user", "permission": []}, {"id": "mosaicml_mpt-30b-chat", "object": "model", "owned_by": "user", "permission": []}, {"id": "OpenAssistant-Llama2-13B-Orca-v2-8K-3166-GPTQ", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_MythoMax-L2-13B-GPTQ_gptq-4bit-32g-actorder_True", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B-GPTQ_gptq-4bit-32g-actorder_True", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_WizardCoder-Python-13B-V1.0-GPTQ", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_WizardCoder-Python-13B-V1.0-GPTQ_gptq-4bit-32g-actorder_True", "object": "model", "owned_by": "user", "permission": []}, {"id": "TheBloke_WizardCoder-Python-13B-V1.0-GPTQ_gptq-8bit-128g-actorder_True", "object": "model", "owned_by": "user", "permission": []}, {"id": "vicuna-13b-v1.5-16k.Q5_K_M.gguf", "object": "model", "owned_by": "user", "permission": []}, {"id": "Wizard-Vicuna-13B-Uncensored.Q5_K_M.gguf", "object": "model", "owned_by": "user", "permission": []}, {"id": "wizardcoder-python-34b-v1.0.Q5_K_M.gguf", "object": "model", "owned_by": "user", "permission": []}, {"id": "WizardLM-WizardCoder-Python-13B-V1.0.Q6_K.gguf", "object": "model", "owned_by": "user", "permission": []}]}

I tried setting up the Model like this:

![image](https://github.com/purton-tech/bionicgpt/assets/69261029/83977874-da24-489b-9fc3-6801920f55b8)


When I try sending a test message I get this response in the console:

[bionicgpt-db-1              | 2023-10-06 00:33:07.798 UTC [62] LOG:  checkpoint starting: time
bionicgpt-db-1              | 2023-10-06 00:33:08.036 UTC [62] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.207 s, sync=0.009 s, total=0.238 s; sync files=3, longest=0.005 s, average=0.003 s; distance=2 kB, estimate=1389 kB
bionicgpt-barricade-1       | [2023-10-06T00:33:29Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 408.200µs
bionicgpt-barricade-1       | [2023-10-06T00:33:29Z INFO  sqlx::query] SELECT id, user_id, session_verifier, …; rows affected: 0, rows returned: 1, elapsed: 461.701µs
bionicgpt-barricade-1       |
bionicgpt-barricade-1       |     SELECT
bionicgpt-barricade-1       |       id,
bionicgpt-barricade-1       |       user_id,
bionicgpt-barricade-1       |       session_verifier,
bionicgpt-barricade-1       |       otp_code_confirmed,
bionicgpt-barricade-1       |       otp_code_encrypted,
bionicgpt-barricade-1       |       otp_code_attempts,
bionicgpt-barricade-1       |       otp_code_sent
bionicgpt-barricade-1       |     FROM
bionicgpt-barricade-1       |       sessions
bionicgpt-barricade-1       |     WHERE
bionicgpt-barricade-1       |       id = $1
bionicgpt-barricade-1       |
bionicgpt-barricade-1       | [2023-10-06T00:33:29Z INFO  actix_web::middleware::logger] 172.18.0.3 "POST /app/team/1/send_message HTTP/1.1" 200 0 "-" "-" 0.001286
bionicgpt-barricade-1       | [2023-10-06T00:33:29Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 257.800µs](url)

So far it's there is no response by the model but perhaps this is getting closer. I get the sense that I'm probably just not following your instructions correctly.
